package com.jev.probe.jev

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Pins the Kotlin renderer to the official Python reference ("macjev-render-v1").
 *
 * GENERATED by tools/jev_local/emit_render_test.py from the vectors that the
 * release's own jev_style_decision.py produces with the same fake tokenizer.
 * Do not hand-edit: re-run the generator after any renderer change.
 *
 * The fake tokenizer makes the layout observable without a model or a device:
 * it is the token boundaries, option order and " ->" slot arithmetic that go
 * wrong in a port, not the arithmetic inside llama.cpp.
 */
class LocalJevRendererTest {

    /** Must match fake_encode() in tools/jev_local/render_parity.py. */
    private fun fakeEncode(text: String): IntArray = when (text) {
        " yes" -> intArrayOf(9542)
        " no" -> intArrayOf(874)
        " ->" -> intArrayOf(1411)
        else -> IntArray(text.length) { i -> 2000 + (text[i].code % 1000) }
    }

    private val renderer = LocalJevRenderer(9542, 874, ::fakeEncode)

    private val stateJson = "{\"chat\": {\"relationship\": \"colleague\", \"latest_from\": \"other\", \"messages\": [{\"from\": \"other\", \"text\": \"ok\"}]}}"

    private val question = JSONObject(
        "{\"type\": \"choice\", \"instructions\": \"Which one?\", \"criteria\": {\"alpha\": \"first option\", \"beta\": \"second option\", \"gamma\": \"third option\"}}"
    )

    private val expectedIds = intArrayOf(
        2083, 2116, 2097, 2116, 2101, 2058, 2010, 2123, 2034, 2099, 2104, 2097, 2116, 2034, 2058, 2032,
        2123, 2034, 2114, 2101, 2108, 2097, 2116, 2105, 2111, 2110, 2115, 2104, 2105, 2112, 2034, 2058,
        2032, 2034, 2099, 2111, 2108, 2108, 2101, 2097, 2103, 2117, 2101, 2034, 2044, 2032, 2034, 2108,
        2097, 2116, 2101, 2115, 2116, 2095, 2102, 2114, 2111, 2109, 2034, 2058, 2032, 2034, 2111, 2116,
        2104, 2101, 2114, 2034, 2044, 2032, 2034, 2109, 2101, 2115, 2115, 2097, 2103, 2101, 2115, 2034,
        2058, 2032, 2091, 2123, 2034, 2102, 2114, 2111, 2109, 2034, 2058, 2032, 2034, 2111, 2116, 2104,
        2101, 2114, 2034, 2044, 2032, 2034, 2116, 2101, 2120, 2116, 2034, 2058, 2032, 2034, 2111, 2107,
        2034, 2125, 2093, 2125, 2125, 2010, 2010, 2081, 2117, 2101, 2115, 2116, 2105, 2111, 2110, 2032,
        2091, 2099, 2104, 2111, 2105, 2099, 2101, 2093, 2058, 2032, 2087, 2104, 2105, 2099, 2104, 2032,
        2111, 2110, 2101, 2063, 2010, 2079, 2112, 2116, 2105, 2111, 2110, 2115, 2058, 2010, 2045, 2032,
        2097, 2108, 2112, 2104, 2097, 2058, 2032, 2102, 2105, 2114, 2115, 2116, 2032, 2111, 2112, 2116,
        2105, 2111, 2110, 2010, 2045, 2032, 2098, 2101, 2116, 2097, 2058, 2032, 2115, 2101, 2099, 2111,
        2110, 2100, 2032, 2111, 2112, 2116, 2105, 2111, 2110, 2010, 2045, 2032, 2103, 2097, 2109, 2109,
        2097, 2058, 2032, 2116, 2104, 2105, 2114, 2100, 2032, 2111, 2112, 2116, 2105, 2111, 2110, 2010,
        2074, 2117, 2100, 2103, 2101, 2032, 2101, 2097, 2099, 2104, 2032, 2111, 2112, 2116, 2105, 2111,
        2110, 2058, 2010, 2097, 2108, 2112, 2104, 2097, 2058, 2032, 2102, 2105, 2114, 2115, 2116, 2032,
        2111, 2112, 2116, 2105, 2111, 2110, 1411, 2010, 2098, 2101, 2116, 2097, 2058, 2032, 2115, 2101,
        2099, 2111, 2110, 2100, 2032, 2111, 2112, 2116, 2105, 2111, 2110, 1411, 2010, 2103, 2097, 2109,
        2109, 2097, 2058, 2032, 2116, 2104, 2105, 2114, 2100, 2032, 2111, 2112, 2116, 2105, 2111, 2110,
        1411, 2010
    )

    @Test
    fun matchesReferenceRenderer() {
        val r = renderer.render(stateJson, question)
        assertEquals(listOf("alpha", "beta", "gamma"), r.names)
        assertEquals("choice", r.qtype)
        assertEquals(306, r.ids.size)
        assertArrayEquals(expectedIds, r.ids)
        assertArrayEquals(intArrayOf(262, 283, 304), r.slots)
    }

    /**
     * The state string the judge sends must match Python json.dumps spacing
     * (", " and ": "), because the rendered state is tokenised.
     *
     * Key ORDER can only be asserted on Android: its JSONObject is a
     * LinkedHashMap, while the JVM's org.json is a HashMap. So this checks the
     * separators, quoting and array/scalar rendering on a single-key object,
     * and the full ordered string is covered on-device instead.
     */
    @Test
    fun pythonJsonMatchesJsonDumpsSpacing() {
        val state = JSONObject()
            .put("a", JSONArray().put("x").put(1).put(true).put(JSONObject.NULL))
        assertEquals("""{"a": ["x", 1, true, null]}""", LocalJudgeClient.pythonJson(state))
    }
}
